# Generated by Django 6.0 on 2025-12-05 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг (для URL)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('city', models.CharField(choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('other', 'Другой город')], max_length=50, verbose_name='Город')),
                ('uni_type', models.CharField(choices=[('public', 'Государственный'), ('private', 'Частный')], default='public', max_length=20, verbose_name='Тип вуза')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание (для модалки)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='universities/', verbose_name='Главное фото')),
                ('tuition_min', models.PositiveIntegerField(help_text='Например, 1200000', verbose_name='Минимальная стоимость в год, ₸')),
                ('tuition_max', models.PositiveIntegerField(help_text='Например, 1800000', verbose_name='Максимальная стоимость в год, ₸')),
                ('has_grants', models.BooleanField(default=False, verbose_name='Есть гранты')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг (например, 4.6)')),
                ('popularity_score', models.PositiveIntegerField(default=0, verbose_name='Популярность (чем больше, тем больше точка на карте)')),
                ('language_kz', models.BooleanField(default=False, verbose_name='Казахский язык')),
                ('language_ru', models.BooleanField(default=False, verbose_name='Русский язык')),
                ('language_en', models.BooleanField(default=False, verbose_name='Английский язык')),
                ('mobility_access', models.BooleanField(default=False, verbose_name='Доступно для людей с ограниченной мобильностью')),
                ('sign_language', models.BooleanField(default=False, verbose_name='Есть сурдоперевод')),
                ('low_vision_support', models.BooleanField(default=False, verbose_name='Поддержка слабовидящих')),
                ('dormitory_available', models.BooleanField(default=False, verbose_name='Есть общежитие')),
                ('gpa_required', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Минимальный GPA')),
                ('ielts_required', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Минимальный IELTS')),
                ('ent_required', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный балл ЕНТ')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта (для карты)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота (для карты)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='universities', to='core.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('degree_type', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('phd', 'Докторантура')], default='bachelor', max_length=20, verbose_name='Уровень')),
                ('duration_years', models.PositiveIntegerField(default=4, verbose_name='Длительность обучения (лет)')),
                ('language_kz', models.BooleanField(default=False, verbose_name='Казахский язык')),
                ('language_ru', models.BooleanField(default=False, verbose_name='Русский язык')),
                ('language_en', models.BooleanField(default=False, verbose_name='Английский язык')),
                ('tuition_per_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость в год (если отличается от вуза)')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное имя')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('planned_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Планируемый год поступления')),
                ('my_gpa', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Мой GPA')),
                ('my_ielts', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Мой IELTS')),
                ('my_ent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мой балл ЕНТ')),
                ('interested_categories', models.ManyToManyField(blank=True, related_name='interested_users', to='core.category', verbose_name='Интересующие направления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_calculator', models.BooleanField(default=False, verbose_name='Добавлен в Calculator Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_universities', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core.university')),
            ],
            options={
                'verbose_name': 'Сохранённый университет',
                'verbose_name_plural': 'Сохранённые университеты',
                'unique_together': {('user', 'university')},
            },
        ),
    ]
